/* eslint-disable camelcase */
const ImageSet = {
  //tab
  tab1: require('../assets/images/tab/icon_home_2.png'),
  tab1_selected: require('../assets/images/tab/icon_home.png'),
  tab2: require('../assets/images/tab/icon_market_2.png'),
  tab2_selected: require('../assets/images/tab/icon_market.png'),
  tab3: require('../assets/images/tab/icon_trading_2.png'),
  tab3_selected: require('../assets/images/tab/icon_trading.png'),
  tab4: require('../assets/images/tab/icon_assets_2.png'),
  tab4_selected: require('../assets/images/tab/icon_assets.png'),

  financing: require('../assets/images/financing.png'),
  verification_img01: require('../assets/images/Identity_verification_img01.png'),
  verification_img02: require('../assets/images/Identityverification_img02.png'),
  verification_img03: require('../assets/images/Identityverification_img03.png'),
  verification_img04: require('../assets/images/Identityverification_img04.png'),
  verification_img05: require('../assets/images/Identityverification_img05.png'),
  verification_img06: require('../assets/images/Identityverification_img06.png'),
  verification_img07: require('../assets/images/Identityverification_img09.png'),
  verification_img08: require('../assets/images/Identityverification_img08.png'),
  verification_img09: require('../assets/images/Identityverification_btn01.png'),
  verification_img10: require('../assets/images/Identityverification_img07.png'),
  shenfenrenzheng_new: require('../assets/images/shenfenrenzheng_new.png'),
  app_logo: require('../assets/images/icon_login_logo.png'),
  back: require('../assets/images/back.png'),
  icon_duihao: require('../assets/images/icon_duihao.png'),
  icon_hidden: require('../assets/images/icon_hidden.png'),
  icon_hidden_2: require('../assets/images/icon_hidden_2.png'),
  icon_set: require('../assets/images/icon_set.png'),
  icon_transfer: require('../assets/images/icon_transfer.png'),
  icon_billing: require('../assets/images/icon_billing.png'),
  icon_hiddenCash_2: require('../assets/images/icon_hiddenCash_2.png'),
  icon_hiddenCash: require('../assets/images/icon_hiddenCash.png'),
  img_transfer: require('../assets/images/img_transfer.png'),
  icon_conversion: require('../assets/images/icon_conversion.png'),
  icon_next: require('../assets/images/icon_next.png'),
  icon_into: require('../assets/images/icon_into.png'),
  withdrawal: require('../assets/images/withdrawal.png'),
  icon_qb: require('../assets/images/icon_qb.png'),
  icon_cancel_1: require('../assets/images/icon_cancel_1.png'),
  icon_delete_1: require('../assets/images/icon_delete_1.png'),
  gengxin_img01: require('../assets/images/gengxin_img01.png'),
  gengxin_img02: require('../assets/images/gengxin_img02.png'),
  gengxin_img03: require('../assets/images/gengxin_img03.png'),

  // ----------------------tiankun start-----------------------
  icon_radio: require('../assets/images/icon_radio.png'),
  slogan_1: require('../assets/images/slogen_1.png'),
  slogan_2: require('../assets/images/slogen_2.png'),
  home_logo: require('../assets/images/home_logo.png'),
  icon_logo: require('../assets/images/icon_logo.png'),
  banner: require('../assets/images/banner.png'),
  icon_collection: require('../assets/images/icon_collection.png'),
  icon_collection_2: require('../assets/images/icon_collection_2.png'),
  icon_search: require('../assets/images/icon_search.png'),
  icon_cancel: require('../assets/images/icon_cancle.png'),
  icon_sorting_up: require('../assets/images/icon_sorting_1.png'),
  icon_sorting_default: require('../assets/images/icon_sorting_2.png'),
  icon_sorting_down: require('../assets/images/icon_sorting_3.png'),
  icon_wallet: require('../assets/images/icon_wallet.png'),
  img_miss: require('../assets/images/img_miss.png'),
  // ----------------------tiankun end-----------------------

  //===================================董建
  fingerprint_landing_img02: require('../assets/images/fingerprint_landing_img02.png'),
  img_drag_1: require('../assets/images/img_drag_1.png'),
  icon_currency: require('../assets/images/icon_currency.png'),
  icon_information: require('../assets/images/icon_information.png'),
  icon_jia: require('../assets/images/icon_jia.png'),
  icon_jian: require('../assets/images/icon_jian.png'),
  icon_movements: require('../assets/images/icon_movements.png'),
  icon_order_buy: require('../assets/images/icon_order_buy.png'),
  icon_order_sell: require('../assets/images/icon_order_sell.png'),
  icon_order: require('../assets/images/icon_order.png'),
  img_drag_2: require('../assets/images/img_drag_2.png'),
  img_progress_2: require('../assets/images/img_progress_3.png'),
  img_progress_1: require('../assets/images/img_progress_2.png'),
  img_progress: require('../assets/images/img_progress.png'),
  icon_dropdown_2: require('../assets/images/icon_dropdown_2.png'),
  icon_close: require('../assets/images/icon_close.png'),
  icon_copy: require('../assets/images/icon_copy.png'),
  icon_login_logo: require('../assets/images/icon_login_logo.png'),
  jingjia: require('../assets/images/jingjia.png'),

  guide_1: require('../assets/images/guide_1.png'),
  guide_2: require('../assets/images/guide_2.png'),
  guide_3: require('../assets/images/guide_3.png'),
  experience: require('../assets/images/experience.png'),
  icon_choice: require('../assets/images/Choice.png'),
};

export default ImageSet;
